// Generated from reserved-names.json by scripts/gen-reserved-names.ts.
// Do not edit by hand — edit the JSON and regenerate. See constants.ts for what
// this list is and how to change it.

/** §4.1 rule 6, the published half. Frozen: a consensus input, not a setting. */
export const RESERVED_NAMES = Object.freeze([
  'abuse',
  'admin',
  'amazon',
  'apple',
  'binance',
  'bitcoin',
  'bitfinex',
  'bitget',
  'bybit',
  'circle',
  'coinbase',
  'contact',
  'crypto',
  'discord',
  'ethereum',
  'exchange',
  'exodus',
  'facebook',
  'foundation',
  'github',
  'google',
  'kraken',
  'kucoin',
  'ledger',
  'market',
  'marketplace',
  'mastercard',
  'metamask',
  'microsoft',
  'money',
  'names',
  'nimiq',
  'nimiqhub',
  'nimiqpay',
  'official',
  'paypal',
  'phantom',
  'polygon',
  'postmaster',
  'protocol',
  'register',
  'revolut',
  'security',
  'selfcrypto',
  'solana',
  'sonar',
  'staking',
  'store',
  'stripe',
  'support',
  'system',
  'telegram',
  'tether',
  'treasury',
  'trezor',
  'trustwallet',
  'validator',
  'wallet',
] as const)
